"""empty message

Revision ID: a0d1dc2a93a0
Revises: 
Create Date: 2017-04-03 15:56:31.273933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d1dc2a93a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emoji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imgSrc', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('descript', sa.String(), nullable=True),
    sa.Column('likes', sa.String(), nullable=True),
    sa.Column('creatTime', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emoji')
    # ### end Alembic commands ###
